#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("managedandroid.Resource", IsApplication = false)]

namespace managedandroid
{


	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{

		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}

		public partial class String
		{

			// aapt resource value: 0x7f030003
			public static int THIS_IS_CAPS = 2130903043;

			// aapt resource value: 0x7f030002
			public static int applicationName = 2130903042;

			// aapt resource value: 0x7f030001
			public static int hello = 2130903041;

			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}

			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591