#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("managedandroid.Resource", IsApplication = false)]

namespace managedandroid
{


	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{

		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}

		public partial class Attribute
		{

			// aapt resource value: 0x7f010000
			public static int hello = 2130771968;

			// breaks due to readonly
			public static readonly int break_readonly = 1;

			// breaks due to const
			public const int break_const = 1;

			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}

			private Attribute()
			{
			}
		}

		public partial class Id
		{

			// aapt resource value: 0x7f040000
			public static int text = 2130968576;

			// breaks due to "fixed" keyword
			public static int @fixed = 2131165240;

			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}

			private Id()
			{
			}
		}

		public partial class Layout
		{

			// aapt resource value: 0x7f020000
			public static int customView = 2130837504;

			// aapt resource value: 0x7f020001
			public static int hello = 2130837505;

			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}

			private Layout()
			{
			}
		}

		public partial class String
		{

			// aapt resource value: 0x7f030001
			public static int hello = 2130903041;

			// aapt resource value: 0x7f030000
			public static int library_name = 2130903040;

			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}

			private String()
			{
			}
		}

		public partial class Styleable
		{

			public static int[] Theme = new int[] {
										2130771968};

			// aapt resource value: 0
			public static int Theme_hello = 0;

			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}

			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591