using System;
using System.Collections.Generic;
using CppSharp;
using CppSharp.AST;
using CppSharp.Generators;
using Template = CppSharp.Generators.Template;

namespace MonoEmbeddinator4000.Generators
{
    public class JavaGenerator : Generator
    {
        public JavaGenerator(BindingContext context) : base(context)
        {
        }

        public override List<Template> Generate(TranslationUnit unit)
        {
            var sources = new JavaSources(Context, unit);

            return new List<Template> { sources };
        }

        public static string GenId(string id)
        {
            return "__" + id;
        }

        public static string AssemblyId(TranslationUnit unit)
        {
            return GenId(unit.FileName).Replace('.', '_');
        }

        public static JavaTypePrinter GetJavaTypePrinter()
        {
            var typePrinter = new JavaTypePrinter
            {
                PrintScopeKind = CppTypePrintScopeKind.Qualified,
                PrintVariableArrayAsPointers = true
            };

            return typePrinter;
        }
    }

    public abstract class JavaTemplate : Template
    {
        public TranslationUnit Unit;

        public JavaTemplate(BindingContext context, TranslationUnit unit)
            : base(context, unit)
        {
            Unit = unit;
        }

        public string GeneratedIdentifier(string id)
        {
            return CGenerator.GenId(id);
        }

        public string QualifiedName(Declaration decl)
        {
            if (Options.GeneratorKind == GeneratorKind.CPlusPlus)
                return decl.Name;

            return decl.QualifiedName;
        }

        public CManagedToNativeTypePrinter CTypePrinter
        {
            get
            {
                return CGenerator.GetCTypePrinter(Options.GeneratorKind);
            }
        }

        public bool VisitDeclContext(DeclarationContext ctx)
        {
            foreach (var decl in ctx.Declarations)
                if (!decl.Ignore)
                    decl.Visit(this);

            return true;
        }

        public void WriteInclude(string include)
        {
            if (Options.GenerateSupportFiles)
                WriteLine("#include \"{0}\"", include);
            else
                WriteLine("#include <{0}>", include);
        }

        public void GenerateFilePreamble()
        {
            WriteLine("/*");
            WriteLine(" * This is autogenerated code.");
            WriteLine(" * Do not edit this file or all your changes will be lost after re-generation.");
            WriteLine(" */");
        }

        public virtual void GenerateMethodSignature(Method method, bool isSource = true)
        {
            var @class = method.Namespace as Class;
            var retType = method.ReturnType.Visit(CTypePrinter);

            Write("{0}{1} {2}_{3}(", isSource ? string.Empty : "MONO_M2N_API ",
                retType, @class.QualifiedName, method.Name);

            Write(CTypePrinter.VisitParameters(method.Parameters));

            Write(")");
        }

        public virtual string GenerateClassObjectAlloc(string type)
        {
            return $"({type}*) calloc(1, sizeof({type}))";
        }

        public override bool VisitTypedefDecl(TypedefDecl typedef)
        {
            PushBlock();

            var typeName = typedef.Type.Visit(CTypePrinter);
            WriteLine("typedef {0} {1};", typeName, typedef.Name);

            var newlineKind = NewLineKind.BeforeNextBlock;

            var declarations = typedef.Namespace.Declarations;
            var newIndex = declarations.FindIndex(d => d == typedef) + 1;
            if (newIndex < declarations.Count)
            {
                if (declarations[newIndex] is TypedefDecl)
                    newlineKind = NewLineKind.Never;
            }

            PopBlock(newlineKind);

            return true;
        }

        public override bool VisitNamespace (Namespace @namespace)
        {
            return VisitDeclContext(@namespace);
        }

        public override bool VisitFieldDecl(Field field)
        {
            WriteLine("{0} {1};", field.Type, field.Name);
            return true;
        }

        public override bool VisitProperty(Property property)
        {
            return true;
        }
    }
}
