# GNU Make project makefile autogenerated by Premake

ifndef config
  config=release
endif

ifndef verbose
  SILENT = @
endif

.PHONY: clean prebuild prelink

ifeq ($(config),release)
  TARGETDIR = .
  TARGET = $(TARGETDIR)/Basic.Gen
  define BUILDCMDS
	@echo Running build commands
	mono --debug ../../build/lib/Debug/MonoEmbeddinator4000.exe -gen=c -out=c -p=macos -compile -target=shared Basic.Managed.dll
	mono --debug ../../build/lib/Debug/MonoEmbeddinator4000.exe -gen=objc -out=objc -p=macos -compile -target=shared Basic.Managed.dll
	mono --debug ../../build/lib/Debug/MonoEmbeddinator4000.exe -gen=java -out=java -p=macos -target=shared Basic.Managed.dll
  endef
  define CLEANCMDS
  endef
endif

$(TARGET):
	$(BUILDCMDS)

clean:
	$(CLEANCMDS)
